---
title: 'Tipologia y Ciclo de vida de los Datos. Practica 2'
author: "Autores: Alexis Arroyo y  Gabriel Pulido de Torres"
date: "Enero 2020"
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 2
    includes:
      in_header: PRA-header.html
  pdf_document:
    highlight: zenburn
    toc: yes
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval=T, echo=T)
```

******
# Introducción
******
# Descripción del dataset. ¿Por qué es importante y qué pregunta/problema pretende responder?
******
# Integración y selección de los datos de interés a analizar.
******
# Limpieza de los datos.

## ¿Los datos contienen ceros o elementos vacíos? ¿Cómo gestionarías cada uno de estos casos?

## Identificación y tratamiento de valores extremos.
******
# Análisis de los datos.

## Selección de los grupos de datos que se quieren analizar/comparar (planificación de los análisis a aplicar).

## Comprobación de la normalidad y homogeneidad de la varianza.

## Aplicación de pruebas estadísticas para comparar los grupos de datos. 

En función de los datos y el objetivo del estudio, aplicar pruebas de contraste de hipótesis,
correlaciones, regresiones, etc. Aplicar al menos tres métodos de análisis diferentes.

******
# Representación de los resultados a partir de tablas y gráficas.
******
# Resolución del problema. A partir de los resultados obtenidos, ¿cuáles son las conclusiones? ¿Los resultados permiten responder al problema?



